### ISSUE TITLE
A new object-mapper is created every time something is logged

### ISSUE THREAD

**Issue by miikka** [viesti/timbre-json-appender#1]
A micro-optimization, maybe, but one instance would be good enough for the whole logger lifetime.

**Comment by viesti** [comment]
Ah, true, an obvious oversight! 

On a sidenote, for some reason I had notifications turned off so I didn't notice these comments, sorry for the lag :)

**Comment by viesti** [comment]
Fixed in 29f945a95cba005ea943144e271e52a7803cdee1, thanks for the report!
