### ISSUE TITLE
Include default fields: host, namespace:file number

### ISSUE THREAD

**Issue by Limess** [viesti/timbre-json-appender#17]
By default the timbre `println-appender` will print the host as well as the namespace and line number where the log line occurred:

```
2021-04-09T16:03:30.292Z ip-192-168-0-14.eu-west-1.compute.internal INFO main [signal.logging:125] - Logging initialised :min-level [["taoensso.*" :error] ["signal.*" :debug] ["*" :warn]] :json false
```

These aren't included in this appender:

```json
{
  "timestamp" : "2021-04-09T16:05:09Z",
  "level" : "info",
  "thread" : "main",
  "msg" : "Logging initialised",
  "args" : {
    "min-level" : [ [ "taoensso.*", "error" ], [ "signal.*", "debug" ], [ "*", "warn" ] ],
    "json" : true
  }
}
```

It'd be useful to include these so as to act as a drop-in replacement for the default appender.

**Comment by viesti** [comment]
True, good point! Maybe even have a way to configure fields to include, and have good defaults.
