### ISSUE TITLE
Requesting option to customize the key of the `msg` field

### ISSUE THREAD

**Issue by pieterbreed** [viesti/timbre-json-appender#21]
Hi, thanks for working on this library.

I'm currently logging in an environment where logz.io is used for handling logs. This log parsing fails on `msg` field, because it expects that field to be called `message`. The behaviour that I'm seeing is that all the fields are extracted correctly except for `message` (because it doesn't exist when using this output). Then logz.io displays the entire JSON string for the `message`.

This could be fixed if I could configure the key for this field to be `:message` instead of `:msg`. 

I don't mind working on a pull request for this. Is this even a feature you would consider?

**Comment by viesti** [comment]
Sounds like a nice idea, I'd be happy to see a PR :)
