### ISSUE TITLE
Log whenever fallbacks happen

### ISSUE THREAD

**Issue by vemv** [viesti/timbre-json-appender#37]
Per 

https://github.com/viesti/timbre-json-appender/blob/ac259e3644ace04bfc97deb8550d90b6c14f3e0b/src/timbre_json_appender/core.clj#L180-L181

, there's a fallback.

While that's pretty sound, in practice in production I occasionally get text logging with no hint of what went wrong.

I'd suggest that the `Throwable _t` was passed to a customizable function, default no-op.

(Personally I would log it 1 out of 10 times or so)

WDYT?

Thanks - V

**Comment by viesti** [comment]
Sounds reasonable, I could take a stab at this, if you don't get to it first :)

**Comment by viesti** [comment]
Happened to have a moment, spiked out something: https://github.com/viesti/timbre-json-appender/commit/4999ace7d86f60de38e6d7e6272071db1cf73393

Could do release later, if this looks kosher.

**Comment by vemv** [comment]
Good morning, thanks much! Simple and effective.

Looking forward to a release.

**Comment by viesti** [comment]
Released the change as 0.2.13. Cheers!

**Comment by vemv** [comment]
🍻 trying it out
