### ISSUE TITLE
It looks like the latest version with inlining args support is not on clojars/maven?

### ISSUE THREAD

**Issue by xlfe** [viesti/timbre-json-appender#7]

**Comment by viesti** [comment]
Ah true, have been lazy :), I'll push a version 0.1.1 with inline args in near future :) If you'r using deps.edn, you can use git deps for the time being.

**Comment by viesti** [comment]
Pushed 0.1.1 now to Clojars also.

**Comment by xlfe** [comment]
Thanks @viesti
