### ISSUE TITLE
How to combine with timbre's `with-context`?

### ISSUE THREAD

**Issue by xlfe** [viesti/timbre-json-appender#8]
Firstly thank you for making this library available!

Just wondering if it is possible to use timbre's with-context to add args to the log context?

Appreciate your thoughts, or whether you'd like a PR to do that?

Cheers

**Comment by viesti** [comment]
Ah, that would be a nice idea! The `:context` key in the map that the appender receives could be merged into log-map.

I'd be happy to see a PR that makes this possible :)

**Comment by xlfe** [comment]
thanks @viesti !
